### ISSUE TITLE
Atlas request

### ISSUE THREAD

**Issue by harpe300** [ggseg/ggsegExtra#12]
Dr. Mowinckel,

Thank you for creating this fantastic package! I look forward to using it in my work.

Would it be possible to get the 400-parcel schaefer17 atlas in polygon format? I would love to use it to make figures.

Thank you,
Jeremy

**Comment by harpe300** [comment]
Never mind, I see that

**Comment by Athanasiamo** [comment]
We are currently a behind creating new atlases, but will keep it on the list of things to look into. 

We are working on improving the pipeline for custom creation of atlases, and hope the improvement will ease atlas creation considerably for us and others to add new atlases. We are currently spending most time in trying to make that work nicely. Particularly for high dimension atlases like the 400 parcellation from schaefer, the work to create an atlas now is very cumbersome.

**Comment by neuropil** [comment]
Hello Dr. Mowinckel,

Is the AAL2 atlas available in ggseg or are there plans to include this atlas? Thanks!

Best,
John

**Comment by Athanasiamo** [comment]
we dont have explicit plans on that yet. But we'll put it on the list!

**Comment by neuropil** [comment]
Cool! Thanks!

**Comment by Athanasiamo** [comment]
all the schaefer parcellations can now be found in [ggsegSchaefer](https://github.com/ggseg/ggsegSchaefer)
