### ISSUE TITLE
make_ggseg3d_2_ggseg   :GL_INVALID_OPERATION : glBufferData:

### ISSUE THREAD

**Issue by WillForan** [ggseg/ggsegExtra#30]
We're trying to get a 2d atlas for `100Parcels_7Networks` in [`Schaefer2018`](https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal). But I get `GL_INVALID_OPERATION` errors on all the linux machines I've tried. 

Have I missed a critical step? Or maybe there's a opengl dependency or driver issue?

Thanks!!

Full script is [mkggseg_Y100N7.R](https://github.com/LabNeuroCogDevel/mkggseg_atlas/blob/master/mkggseg_Y100N7.R)
```
Y100N7_2datlas <- make_ggseg3d_2_ggseg(output_dir="2d_orca",
                                       ggseg3d_atlas=Y100N7_segs,
                                       ncores=1)
```
 
> ● 1/7 Snapshotting views of entire atlas to 2d_orca/Yeo100N7
> [184671:0104/101130.485758:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
> ✔ Snapshots complete
> ● 2/7 Snapshotting individual regions to 2d_orca/Yeo100N7/img
> [185471:0104/101221.492563:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
> [186456:0104/101321.881990:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
> [186947:0104/101352.025082:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
> ...

```
Y100N7_2datlas
 # Yeo100N7 cortical brain atlas
  regions: 0 
  hemispheres: left, right 
  side views: lateral, medial 
  palette: yes 
  use: ggplot() + geom_brain() 
 ----
 # … with 5 variables: hemi <chr>, side <chr>, region <chr>, label <chr>,
 #   roi <chr>
```

I think the 3d altas was created successfully:
![image](https://user-images.githubusercontent.com/680742/103555223-d41b5c80-4ea7-11eb-874a-b7941e034783.png)

```
is_ggseg3d_atlas(Y100N7_segs) # TRUE

Y100N7_segs
 # A tibble: 6 x 4
   atlas       surf     hemi  ggseg_3d         
   <chr>       <chr>    <chr> <list>           
 1 Yeo100N7_3d inflated left  <tibble [51 × 7]>
 2 Yeo100N7_3d inflated right <tibble [51 × 7]>


Y100N7_segs$ggseg_3d[[1]]$annot %>% head
[1] "Background+FreeSurfer_Defined_Medial_Wall"
[2] "7Networks_LH_Vis_1"                       
[3] "7Networks_LH_Vis_2"                       
[4] "7Networks_LH_Vis_3"                       
[5] "7Networks_LH_Vis_4"                       
[6] "7Networks_LH_Vis_5" 

p <- ggseg3d::ggseg3d(d %>% filter(grepl('RH_',region)),
                       atlas=mesh_dt, color="T_Value",
                       hemisphere=c("right"))
htmlwidgets::saveWidget(p, selfcontained=T, file=file.path(getwd(),"/example/index.html"))
```

**Comment by Athanasiamo** [comment]
To me, this looks like there is some issue with Orca. It's failing at the stages where Orca is called to snapshot the 3d brain. 

Have you successfully installed Orca? 

https://github.com/plotly/orca#installation

**Comment by WillForan** [comment]
That looks like it! Thanks! Looks like this is an open ocra issue
https://github.com/plotly/orca/issues/127


I'd previously only verified using `orca --help`. But trying to generate an image with orca gives the same error I was seeing in  `make_ggseg3d_2_ggseg`

```
orca graph '{ "data": [{"y": [1,2,1]}] }' -o /tmp/test_orca.png

[283523:0105/085524.595274:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
```

**Comment by Athanasiamo** [comment]
great. That's one problem solved.

I'm a little baffled as to why the regions should end up with NA, with they are correct in the corresponding 3d atlas. The region names are ok in the 3d, but end with with NA in the 2d?

**Comment by WillForan** [comment]
Thanks for the feedback!

I think my environment is still incomplete/unstable. I'll update if I can figure out what's going on.



I changed the output directory and I'm stuck on `snapshotting` for eternally.
```
make_ggseg3d_2_ggseg(output_dir="2d_orca_retry20210114", ggseg3d_atlas=Y100N7_3d, ncores=1)


1/7 Snapshotting views of entire atlas to 2d_orca_retry20210114/Yeo100N7
```

----

At least it looks like R is able to call orca. But all the processes are "sleeping"

```
pstree -Tp 29950
R(29950)───node(30286)───electron(30294)─┬─chrome-sandbox(30296)───electron(30297)───+
                                         ├─electron(30330)
                                         └─electron(30337)



                                         

pstree -p 29950|grep -Po '\d+'|sed 's:.*:/proc/&/status:'|xargs grep -hE Name\|State|paste - -
Name:   R       State:  S (sleeping)
Name:   node    State:  S (sleeping)
Name:   electron        State:  S (sleeping)
Name:   chrome-sandbox  State:  S (sleeping)
Name:   electron        State:  S (sleeping)
Name:   electron        State:  S (sleeping)
Name:   llvmpipe-0      State:  S (sleeping)
....
```

**Comment by Athanasiamo** [comment]
as a test, try setting `ncores = 1`. There might be a parallellization issue
