### ISSUE TITLE
ggsegExtra costum atlases (annot2dpv)

### ISSUE THREAD

**Issue by AnnaFurtjes** [ggseg/ggsegExtra#39]
Dear Dr. Mowinkel, 

Thank you so much for making your ggseg packages available in R! I found them so useful for brain visualisations!

I have been trying to create custom 3D atlases using [this description](https://ggseg.github.io/ggsegExtra/articles/customatlas3d.html) for ggsegExtra, but I cannot find the annot2dpv function (used in the aparc_2_mesh step). For some reason, R doesn't recognise it, and it doesn't seem to have been installed with the package.
Also, I can't seem to find the function on the [ggsegExtra GitHub](https://github.com/ggseg/ggsegExtra/tree/master/R). 

I wondered if it might be possible for you to share this function with me?
Or alternatively, is there another way to create custom atlases without this function?

Thank you so much for taking the time to read this!
Best, 
Anna

**Comment by Athanasiamo** [comment]
Hi Anna!

Can you show me the error message you are getting? The function is in the package, but is not an exported function as its only used internally.

https://github.com/ggseg/ggsegExtra/blob/master/R/fs-utils.R#L583

--Mo

**Comment by AnnaFurtjes** [comment]
Thanks for getting back to me!
I am running:
mri_surf2surf_rereg(subject = "bert",
              annot = "mpm.vpnl",
              hemi = "lh",
			  target_subject = "fsaverage5",
              output_dir = wd)

dt <- make_aparc_2_3datlas(annot = "mpm.vpnl", hemisphere = "lh", surface = "inflated", annot_dir = wd, output_dir = wd, subject = "bert") 

And I get this error message:

Error in `$<-.data.frame`(`*tmp*`, "label", value = c(NA, "FG1", "FG2",  :
  replacement has 9 rows, data has 8

I have tried running this with a couple of different .annot files, and always get the same error message.

Can you tell from this what might be going wrong? 
Thank you so much. 
Best, 
Anna

**Comment by Athanasiamo** [comment]
could you send me the "mpm.vpnl" file you are using, so I could test with that. That would speed things up I think, its a file type I am unfamiliar with.

**Comment by Athanasiamo** [comment]
There is something wrong with the projection.
I talked to the repo maintainer about it, so he's not going to support it anymore. 

https://github.com/faskowit/multiAtlasTT/issues/10
