### ISSUE TITLE
Freesurfer dependency

### ISSUE THREAD

**Issue by araikes** [ggseg/ggsegExtra#53]
Just a note that Freesurfer (https://cran.r-project.org/web/packages/freesurfer/index.html) is archived on CRAN and no longer downloadable.

**Comment by Athanasiamo** [comment]
right. Damn! ok. I'll what I can do about that and getting things installing nicely again!

**Comment by Athanasiamo** [comment]
I've asked if I can help get neurobase up and running again, waiting to hear what failed (as my local copy is passing all checks). 

I'll add neurobase and freesurfer github repos to the ggseg r-universe, which should make it install without manual hacks by users.

**Comment by Athanasiamo** [comment]
https://github.com/ggseg/universe/commit/98134e1c48b5c661a7378aaf73797314e4aaf20b
