### ISSUE TITLE
freesurfer dependency

### ISSUE THREAD

**Issue by butellyn** [ggseg/ggsegExtra#56]
Hi! The `freesurfer` package has been removed from CRAN, so it isn't possible to install `ggsegExtra` at the moment. Do you have a workaround for this?

https://cran.r-project.org/web/packages/freesurfer/index.html

**Comment by drmowinckels** [comment]
Hi!

neurobase was fixed, so I assumed freesurfer would be too. Seems not, yet. 
I'e added the freesurfer repo to the ggseg R-universe, which should make install via R-universe work. It will likely take a couple of hours for the build to complete.

If you see freesurfer pop up in these builds, you can have a go at installing via R-universe

https://ggseg.r-universe.dev/ui#builds

```
# Enable repository from ggseg
 options(repos = c(
 ggseg = 'https://ggseg.r-universe.dev',
 CRAN = 'https://cloud.r-project.org'))
  
 # Download and install ggsegExtra in R
 install.packages('ggsegExtra')
```

**Comment by butellyn** [comment]
It worked! Thank you

**Comment by fhaos123** [comment]
Hi,everyone
Which version of R does it needs for `ggsegExtra` ?
```
https://cran.rstudio.com/bin/windows/Rtools/
Warning in install.packages :
  package ‘ggsegExtra’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```

**Comment by drmowinckels** [comment]
That message is misleading. You cannot install ggsegExtra from CRAN as a normal package, its not there.

You need to do what is stated in the README:

```r
# Enable this universe
options(repos = c(
  ggseg = 'https://ggseg.r-universe.dev',
  CRAN = 'https://cloud.r-project.org'))

# Install some packages
install.packages('ggsegExtra')
```
