### ISSUE TITLE
Atlas wishlist

### ISSUE THREAD

**Issue by Athanasiamo** [ggseg/ggsegExtra#6]
AAL: http://neuro.imm.dtu.dk/wiki/Automated_Anatomical_Labeling

**Comment by johnaeanderson** [comment]
Hi Dr. Mowinckel, thanks so much for creating such a useful tool!  Would it be possible to request the JHU-white matter label atlas?  The JHU tract atlas is great, but I'd like to display the body of the corpus callosum and some other regions which don't currently appear.  

I realize there are a lot of requests at the moment and this might not be a priority - just posting to a) let you know I really appreciate this tool and b) peg this particular atlas

**Comment by Athanasiamo** [comment]
Hi @johnaeanderson !

The JHU already exists, which you can see in the `ggseg_atlas_repos()` overview.

You can find it here: https://github.com/LCBC-UiO/ggsegJHU

**Comment by johnaeanderson** [comment]
The JHU tract atlas is wonderful and I'm using that now, but I was inquiring about the JHU-ICBM-labels atlas which I don't think has been ported (unless I'm missing it somewhere?).   Thanks again!

**Comment by Athanasiamo** [comment]
Hi!
 
Right, sorry I read that a little too fast. While it is implemented in ggseg3d, we have yet to make a version for ggseg. Its planned, but not in the immediate future, as I'm working more on making the atlas creation pipelines in ggsegExtra working better, including attempting to make a pipeline for subortical 2d-atlases ( which we do not have a solution for at the moment).

**Comment by lucasfr** [comment]
Any news about the AAL atlas support? 
I tried to make it myself by converting the nii files (in https://www.gin.cnrs.fr/en/tools/aal/) to .mgz and trying to follow the tutorial. Unfortunately I have not been very successful. 
It would really be great for some work I am developing at the moment to have it on ggseg and ggseg3d.

**Comment by Athanasiamo** [comment]
Hi. We are still currently not making new atlases, but focusing on streamlining the creation pipeline. We cannot promise to get to this soon, but it is on our list of atlases to make once other features are in place.

**Comment by lucasfr** [comment]
Thank you for the update, @Athanasiamo.

**Comment by Athanasiamo** [comment]
@lucasfr we have the AAL supported now in its own repository, [ggsegAal](https://github.com/ggseg/ggsegAal)

@MelisAnaturk the havard oxford cortical parcellation has its own repository now [ggsegHO](https://github.com/ggseg/ggsegHO)

**Comment by lucasfr** [comment]
Thank you very much, @Athanasiamo !

**Comment by songpeilun123** [comment]
AAL116 atlas (most commonly used). [ggsegAal](https://github.com/ggseg/ggsegAal) is based on AAL2.

Tzourio-Mazoyer, N., Landeau, B., Papathanassiou, D., Crivello, F., Etard, O., Delcroix, N., … Joliot, M. (2002). Automated Anatomical Labeling of Activations in SPM Using a Macroscopic Anatomical Parcellation of the MNI MRI Single-Subject Brain. NeuroImage, 15(1), 273–289.

**Comment by drmowinckels** [comment]
Hi all!

I'm finding it hard to keep track of wishes here (and sorry for having little time to make new ones).

Can those of you who still have atlases on your wishlist please add them to the new community discussion forum I made?
I'm hoping I can keep track easier there!

https://github.com/ggseg/discussions/discussions/categories/atlas-wishlist
